name: PR Test

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test

  automerge:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Add automerge label
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
      - name: Verify automerge label
        run: |
          gh pr view $PR_NUMBER --json labels --jq '.labels[].name'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - uses: pascalgn/automerge-action@v0.15.6
        with:
          merge: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
