name : pr-check
on : 
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs : 
  test : 
    runs-on : ubuntu-latest
    steps : 
      - name : checkout
        uses : actions/checkout@v4

      - name : setup
        uses : actions/setup-node@v4
          with : 
            node-version : '20'
      - name : install dependencies
        run : npm install 

      - name : run test
        run  : npm run test