name: Check Only data.txt Changes

on:
  pull_request:
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure only src/assets/data.txt is modified
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          for file in $CHANGED_FILES; do
            if [ "$file" != "src/assets/data.txt" ]; then
              echo "❌ Invalid file modified: $file"
              exit 1
            fi
          done
          echo "✅ Only src/assets/data.txt was changed"

  auto-merge:
    runs-on: ubuntu-latest
    needs: check-file
    if: success()
    steps:
      - name: Add automerge label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge

      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
